// Generated by CoffeeScript 1.12.1
(function() {
  var exports,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  exports = this;

  exports.Obstacle = (function(superClass) {
    extend(Obstacle, superClass);

    function Obstacle() {
      return Obstacle.__super__.constructor.apply(this, arguments);
    }

    return Obstacle;

  })(Torch.Sprite);

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiT2JzdGFjbGUuanMiLCJzb3VyY2VSb290IjoiLi5cXC4uXFwuLiIsInNvdXJjZXMiOlsiR2FtZXNcXFRhbmt5VGFua3NcXFNyY1xcT2JzdGFjbGUuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTtBQUFBLE1BQUEsT0FBQTtJQUFBOzs7RUFBQSxPQUFBLEdBQVU7O0VBRUosT0FBTyxDQUFDOzs7Ozs7Ozs7S0FBaUIsS0FBSyxDQUFDO0FBRnJDIiwic291cmNlc0NvbnRlbnQiOlsiZXhwb3J0cyA9IHRoaXNcclxuXHJcbmNsYXNzIGV4cG9ydHMuT2JzdGFjbGUgZXh0ZW5kcyBUb3JjaC5TcHJpdGVcclxuIl19
//# sourceURL=C:\dev\Torch\Games\TankyTanks\Src\Obstacle.coffee